### ISSUE TITLE
Allowing Waterlogging of the Flopper

### ISSUE THREAD

**Issue by WenXin20** [CyclopsMC/Flopper#12]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Allow the Flopper to be Waterlogged, which makes sense considering it is used to move liquids.

**Comment by rubensworks** [comment]
Sure, makes sense. However, waterlogging probably won't simply be possible by right-clicking with a bucket, as that inserts the fluid into the flopper. So I'll have to think about this a bit.

**Comment by WenXin20** [comment]
You can right-click on the block that's next to or below it to waterlog the block without having to right-click on the Flopper.

**Comment by WenXin20** [comment]
Especially since the Flopper's hitbox doesn't take up the whole block space.

**Comment by rubensworks** [comment]
Ah yes, that makes sense. (I haven't played around with waterlogging mechanics too much yet)

**Comment by rubensworks** [comment]
I just looked into this, and I've decided to not allow waterlogging on floppers after all.
The problem is that waterlogging causes water to be rendered over the block,
which makes it look like there is water is the flopper, which is incorrect:

![2019-11-22_15 57 45](https://user-images.githubusercontent.com/440384/69436029-e76d7600-0d40-11ea-90ca-a389192aa403.png)

I assume that hoppers also don't support waterlogging for this reason.
